config/routes.rb
Rails.application.routes.draw do
  resources :posts do
    resources :comments
  end

  root 'home#index'
  get 'home/about'
  get 'home/help'

  devise_for :users, path: 'accounts', skip: [:sessions, :registrations], controllers: { passwords: "users/passwords" }
  devise_scope :user do 
    resource :registeration, 
              as: 'user_registration',
              except: [:new, :destroy],
              path: 'accounts',
              controller: 'users/registrations'
  end
  as :user do
    get 'login' => 'users/sessions#new', :as => :new_user_session
    post 'login' => 'users/sessions#create', :as => :user_session
    delete 'logout' => 'users/sessions#destroy', :as => :destroy_user_session
    get 'register' => 'users/registrations#new', :as => :new_user_registeration
  end
end

app/views/layouts/_header.html.erb
<ul class="hmenu">
  <% if user_signed_in? %>
    <li>
      <%= link_to 'Posts', posts_path %>
    </li>
    <li>
      <%= link_to('Edit registration', edit_user_registration_path) %>
    </li>
    <li>
      <%= link_to('Logout', destroy_user_session_path, :method => :delete) %>        
    </li>
  <% else %>
    <li>
      <%= link_to('Sign up', new_user_registeration_path) %>        
    </li>
    <li>
      <%= link_to('Login', new_user_session_path)  %>  
    </li>
  <% end %>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DeviseCancancanRails4Demo</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <header>
      <%= render 'layouts/header' %>
    </header>

    <div class="container">
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>

      <%= yield %>
    </div>

    <footer>
    </footer>

  </body>
</html>